swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.huawei.cse.banchmark.base.rest.ClientEndpoint"
  x-java-interface: "gen.swagger.ClientEndpointIntf"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /body:
    post:
      operationId: "body"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "response of 200"
          schema:
            type: "string"